version: "3.9"

services:
  db:
    image: postgres:15
    container_name: security_agency_db
    restart: always
    environment:
      POSTGRES_USER: security_user
      POSTGRES_PASSWORD: security_pass
      POSTGRES_DB: security_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: security_agency_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://security_user:security_pass@db:5432/security_db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python app.py"

volumes:
  postgres_data:
